import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Activity, ArrowLeft, LogOut, Target, Trash2, Sparkles, Share2, Download, FileText } from "lucide-react";
import jsPDF from 'jspdf';
import { Link, useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

interface Goal {
  id: string;
  goal_type: string;
  target_value: number;
  current_value: number | null;
  deadline: string | null;
  status: string;
  created_at: string;
}

interface DayPlan {
  food: string;
  exercise: string;
  activities: string;
  reminder: string;
}

const Goals = () => {
  const [goals, setGoals] = useState<Goal[]>([]);
  const [loading, setLoading] = useState(true);
  const [dialogOpen, setDialogOpen] = useState(false);
  const navigate = useNavigate();
  const { toast } = useToast();

  const [newGoal, setNewGoal] = useState({
    goal_type: "",
    target_value: "",
    current_value: "",
    deadline: "",
    systolic_target: "",
    diastolic_target: "",
    systolic_current: "",
    diastolic_current: "",
    glucose_target: "",
    glucose_current: "",
  });
  const [generating, setGenerating] = useState(false);
  const [selectedGoal, setSelectedGoal] = useState<Goal | null>(null);
  const [dayPlan, setDayPlan] = useState<Record<string, DayPlan> | null>(null);
  const [latestLog, setLatestLog] = useState<any>(null);



  const downloadPlanAsText = (goal: Goal, plan: Record<string, DayPlan>) => {
    const planText = `📅 ${goal.goal_type.replace('_', ' ').toUpperCase()} PLAN\n\n${Object.entries(plan).map(([day, details]) => {
      return `${day}:\n🍽️ Food: ${details.food}\n🏃 Exercise: ${details.exercise}\n📋 Activities: ${details.activities}\n⏰ Reminder: ${details.reminder}`;
    }).join('\n\n')}\n\nGenerated by HealthTrack App`;

    const blob = new Blob([planText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${goal.goal_type}_plan.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Downloaded!",
      description: "Plan downloaded as text file.",
    });
  };

  const savePlanAsPDF = (goal: Goal, plan: Record<string, DayPlan>) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let yPosition = 20;

    // Title
    doc.setFontSize(18);
    doc.text(`${goal.goal_type.replace('_', ' ').toUpperCase()} PLAN`, pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 20;

    // Goal details
    doc.setFontSize(12);
    doc.text(`Target: ${goal.target_value}`, 20, yPosition);
    yPosition += 10;
    if (goal.deadline) {
      doc.text(`Deadline: ${new Date(goal.deadline).toLocaleDateString()}`, 20, yPosition);
      yPosition += 10;
    }
    yPosition += 10;

    Object.entries(plan).forEach(([day, details]) => {
      if (yPosition > pageHeight - 60) {
        doc.addPage();
        yPosition = 20;
      }

      doc.setFontSize(14);
      doc.text(day, 20, yPosition);
      yPosition += 10;

      doc.setFontSize(10);
      doc.text(`Food: ${details.food}`, 20, yPosition);
      yPosition += 8;
      doc.text(`Exercise: ${details.exercise}`, 20, yPosition);
      yPosition += 8;
      doc.text(`Activities: ${details.activities}`, 20, yPosition);
      yPosition += 8;
      doc.text(`Reminder: ${details.reminder}`, 20, yPosition);
      yPosition += 15;
    });

    doc.save(`${goal.goal_type}_plan.pdf`);

    toast({
      title: "PDF Downloaded!",
      description: "Plan saved as PDF file.",
    });
  };

  useEffect(() => {
    checkAuth();
    fetchGoals();
    fetchLatestLog();
  }, []);

  const checkAuth = async () => {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      navigate("/auth");
    }
  };

  const fetchGoals = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;

      const { data, error } = await supabase
        .from("health_goals")
        .select("*")
        .eq("user_id", user.id)
        .order("created_at", { ascending: false });

      if (error) throw error;
      setGoals(data || []);
    } catch (error) {
      console.error("Error fetching goals:", error);
    } finally {
      setLoading(false);
    }
  };

  const fetchLatestLog = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;

      const { data, error } = await supabase
        .from("daily_health_logs")
        .select("*")
        .eq("user_id", user.id)
        .order("log_date", { ascending: false })
        .limit(1)
        .single();

      if (error && error.code !== 'PGRST116') throw error; // PGRST116 is "not found"
      setLatestLog(data);
    } catch (error) {
      console.error("Error fetching latest log:", error);
    }
  };

  const handleSignOut = async () => {
    await supabase.auth.signOut();
    navigate("/");
  };

  const handleGenerateTarget = async () => {
    if (!newGoal.goal_type) {
      toast({
        title: "Error",
        description: "Please select a goal type first.",
        variant: "destructive",
      });
      return;
    }

    setGenerating(true);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("Not authenticated");

      // Fetch user's health data
      const { data: healthData, error: healthError } = await supabase
        .from("health_assessments")
        .select("*")
        .eq("user_id", user.id)
        .order("created_at", { ascending: false })
        .limit(1)
        .single();

      if (healthError) throw healthError;

      const { data, error } = await supabase.functions.invoke("generate-goals", {
        body: {
          goal_type: newGoal.goal_type,
          current_value: newGoal.current_value ? parseFloat(newGoal.current_value) : null,
          deadline: newGoal.deadline || null,
          healthData,
        },
      });

      if (error) throw error;

      setNewGoal({ ...newGoal, target_value: data.suggested_target.toString() });
      toast({
        title: "Target Generated!",
        description: "AI has suggested a realistic target.",
      });
    } catch (error: any) {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    } finally {
      setGenerating(false);
    }
  };

  const handleViewPlan = async (goal: Goal) => {
    setSelectedGoal(goal);
    setGenerating(true);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("Not authenticated");

      // Fetch user's health data
      const { data: healthData, error: healthError } = await supabase
        .from("health_assessments")
        .select("*")
        .eq("user_id", user.id)
        .order("created_at", { ascending: false })
        .limit(1)
        .single();

      if (healthError) throw healthError;

      const { data, error } = await supabase.functions.invoke("generate-goals", {
        body: {
          goal_type: goal.goal_type,
          current_value: goal.current_value || healthData.weight,
          deadline: goal.deadline,
          healthData,
        },
      });

      if (error) throw error;

      setDayPlan(data.plan);
    } catch (error: any) {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    } finally {
      setGenerating(false);
    }
  };

  const handleCreateGoal = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("Not authenticated");

      let targetValue: number;
      let currentValue: number | null = null;

      if (newGoal.goal_type === "blood_pressure") {
        targetValue = parseFloat(newGoal.systolic_target);
        if (newGoal.systolic_current) currentValue = parseFloat(newGoal.systolic_current);
      } else if (newGoal.goal_type === "blood_glucose") {
        targetValue = parseFloat(newGoal.glucose_target);
        if (newGoal.glucose_current) currentValue = parseFloat(newGoal.glucose_current);
      } else {
        targetValue = parseFloat(newGoal.target_value);
        if (newGoal.current_value) currentValue = parseFloat(newGoal.current_value);
      }

      const goalData: any = {
        user_id: user.id,
        goal_type: newGoal.goal_type,
        target_value: targetValue,
        status: "active",
      };

      if (currentValue !== null) goalData.current_value = currentValue;
      if (newGoal.deadline) goalData.deadline = newGoal.deadline;

      const { error } = await supabase.from("health_goals").insert(goalData);

      if (error) throw error;

      toast({
        title: "Goal Created!",
        description: "Your health goal has been added.",
      });

      setNewGoal({
        goal_type: "",
        target_value: "",
        current_value: "",
        deadline: "",
        systolic_target: "",
        diastolic_target: "",
        systolic_current: "",
        diastolic_current: "",
        glucose_target: "",
        glucose_current: "",
      });
      setDialogOpen(false);
      fetchGoals();
    } catch (error: any) {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    }
  };

  const handleDeleteGoal = async (id: string) => {
    try {
      const { error } = await supabase.from("health_goals").delete().eq("id", id);

      if (error) throw error;

      toast({
        title: "Goal Deleted",
        description: "Goal has been removed.",
      });
      fetchGoals();
    } catch (error: any) {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    }
  };

  const getProgress = (goal: Goal): number => {
    if (!goal.current_value) return 0;

    // For weight_loss, calculate progress based on latest log weight vs target
    if (goal.goal_type === "weight_loss") {
      if (!latestLog?.weight) return 0;
      const currentWeight = latestLog.weight;
      const targetWeight = goal.target_value;
      const initialWeight = goal.current_value; // Starting weight from goal creation

      if (currentWeight <= targetWeight) return 100; // Goal achieved
      if (currentWeight >= initialWeight) return 0; // No progress

      const totalToLose = initialWeight - targetWeight;
      const lostSoFar = initialWeight - currentWeight;
      return Math.min((lostSoFar / totalToLose) * 100, 100);
    }

    // For weight_gain, calculate progress based on latest log weight vs target
    if (goal.goal_type === "weight_gain") {
      if (!latestLog?.weight) return 0;
      const currentWeight = latestLog.weight;
      const targetWeight = goal.target_value;
      const initialWeight = goal.current_value; // Starting weight from goal creation

      if (currentWeight >= targetWeight) return 100; // Goal achieved
      if (currentWeight <= initialWeight) return 0; // No progress

      const totalToGain = targetWeight - initialWeight;
      const gainedSoFar = currentWeight - initialWeight;
      return Math.min((gainedSoFar / totalToGain) * 100, 100);
    }

    // For exercise, use latest log exercise minutes
    if (goal.goal_type === "exercise") {
      if (!latestLog?.exercise_minutes) return 0;
      return Math.min((latestLog.exercise_minutes / goal.target_value) * 100, 100);
    }

    // For blood_pressure, check if latest systolic is below target
    if (goal.goal_type === "blood_pressure") {
      if (!latestLog?.blood_pressure_systolic) return 0;
      return latestLog.blood_pressure_systolic <= goal.target_value ? 100 : 0;
    }

    // For blood_glucose, check if latest glucose is below target
    if (goal.goal_type === "blood_glucose") {
      if (!latestLog?.blood_glucose) return 0;
      return latestLog.blood_glucose <= goal.target_value ? 100 : 0;
    }

    // For other goals, assume current_value is progress towards target_value
    return Math.min((goal.current_value / goal.target_value) * 100, 100);
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-background to-secondary/20 flex items-center justify-center">
        <Activity className="h-12 w-12 text-primary animate-pulse" />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-secondary/20">
      <header className="container mx-auto px-4 py-6 flex items-center justify-between border-b">
        <div className="flex items-center gap-2">
          <Activity className="h-8 w-8 text-primary" />
          <span className="text-2xl font-bold">HealthTrack</span>
        </div>
        <Button variant="ghost" onClick={handleSignOut}>
          <LogOut className="h-4 w-4 mr-2" />
          Sign Out
        </Button>
      </header>

      <div className="container mx-auto px-4 py-8">
        <div className="mb-8 flex justify-between items-center">
          <div>
            <Link to="/dashboard" className="inline-flex items-center gap-2 text-primary hover:underline mb-4">
              <ArrowLeft className="h-4 w-4" />
              Back to Dashboard
            </Link>
            <h1 className="text-3xl font-bold mb-2">Health Goals</h1>
            <p className="text-muted-foreground">Set and track your health objectives</p>
          </div>
          <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
            <DialogTrigger asChild>
              <Button>
                <Target className="h-4 w-4 mr-2" />
                New Goal
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Create New Goal</DialogTitle>
              </DialogHeader>
              <div className="space-y-4">
                <div className="space-y-2">
                  <Label>Goal Type</Label>
                  <Select value={newGoal.goal_type} onValueChange={(value) => setNewGoal({ ...newGoal, goal_type: value })}>
                    <SelectTrigger>
                      <SelectValue placeholder="Select goal type" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="weight_loss">Weight Loss</SelectItem>
                      <SelectItem value="weight_gain">Weight Gain</SelectItem>
                      <SelectItem value="exercise">Exercise Minutes</SelectItem>
                      <SelectItem value="blood_pressure">Lower Blood Pressure</SelectItem>
                      <SelectItem value="blood_glucose">Lower Blood Glucose</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                {newGoal.goal_type === "blood_pressure" ? (
                  <>
                    <div className="space-y-2">
                      <Label>Blood Pressure Target</Label>
                      <div className="grid grid-cols-2 gap-2">
                        <div>
                          <Label htmlFor="systolic-target" className="text-sm">Systolic (mmHg)</Label>
                          <Input
                            id="systolic-target"
                            type="number"
                            value={newGoal.systolic_target}
                            onChange={(e) => setNewGoal({ ...newGoal, systolic_target: e.target.value })}
                            placeholder="120"
                          />
                        </div>
                        <div>
                          <Label htmlFor="diastolic-target" className="text-sm">Diastolic (mmHg)</Label>
                          <Input
                            id="diastolic-target"
                            type="number"
                            value={newGoal.diastolic_target}
                            onChange={(e) => setNewGoal({ ...newGoal, diastolic_target: e.target.value })}
                            placeholder="80"
                          />
                        </div>
                      </div>
                    </div>
                    <div className="space-y-2">
                      <Label>Current Blood Pressure (optional)</Label>
                      <div className="grid grid-cols-2 gap-2">
                        <div>
                          <Label htmlFor="systolic-current" className="text-sm">Systolic (mmHg)</Label>
                          <Input
                            id="systolic-current"
                            type="number"
                            value={newGoal.systolic_current}
                            onChange={(e) => setNewGoal({ ...newGoal, systolic_current: e.target.value })}
                          />
                        </div>
                        <div>
                          <Label htmlFor="diastolic-current" className="text-sm">Diastolic (mmHg)</Label>
                          <Input
                            id="diastolic-current"
                            type="number"
                            value={newGoal.diastolic_current}
                            onChange={(e) => setNewGoal({ ...newGoal, diastolic_current: e.target.value })}
                          />
                        </div>
                      </div>
                    </div>
                  </>
                ) : newGoal.goal_type === "blood_glucose" ? (
                  <>
                    <div className="space-y-2">
                      <Label htmlFor="glucose-target">Target Blood Glucose (mg/dL)</Label>
                      <Input
                        id="glucose-target"
                        type="number"
                        step="0.1"
                        value={newGoal.glucose_target}
                        onChange={(e) => setNewGoal({ ...newGoal, glucose_target: e.target.value })}
                        placeholder="100"
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="glucose-current">Current Blood Glucose (optional, mg/dL)</Label>
                      <Input
                        id="glucose-current"
                        type="number"
                        step="0.1"
                        value={newGoal.glucose_current}
                        onChange={(e) => setNewGoal({ ...newGoal, glucose_current: e.target.value })}
                      />
                    </div>
                  </>
                ) : (
                  <>
                    <div className="space-y-2">
                      <Label htmlFor="target">Target Value</Label>
                      <div className="flex gap-2">
                        <Input
                          id="target"
                          type="number"
                          step="0.1"
                          value={newGoal.target_value}
                          onChange={(e) => setNewGoal({ ...newGoal, target_value: e.target.value })}
                          placeholder="Enter target or generate with AI"
                        />
                        <Button
                          type="button"
                          variant="outline"
                          onClick={handleGenerateTarget}
                          disabled={generating}
                          className="shrink-0"
                        >
                          <Sparkles className="h-4 w-4 mr-2" />
                          {generating ? "Generating..." : "AI Suggest"}
                        </Button>
                      </div>
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="current">Current Value (optional)</Label>
                      <Input
                        id="current"
                        type="number"
                        step="0.1"
                        value={newGoal.current_value}
                        onChange={(e) => setNewGoal({ ...newGoal, current_value: e.target.value })}
                      />
                    </div>
                  </>
                )}
                <div className="space-y-2">
                  <Label htmlFor="deadline">Deadline (optional)</Label>
                  <Input
                    id="deadline"
                    type="date"
                    value={newGoal.deadline}
                    onChange={(e) => setNewGoal({ ...newGoal, deadline: e.target.value })}
                  />
                </div>
                <Button onClick={handleCreateGoal} className="w-full">
                  Create Goal
                </Button>
              </div>
            </DialogContent>
          </Dialog>
        </div>

        {goals.length === 0 ? (
          <Card className="p-12 text-center">
            <Target className="h-16 w-16 text-primary mx-auto mb-4" />
            <p className="text-muted-foreground mb-4">No goals yet. Set your first health goal!</p>
            <Button onClick={() => setDialogOpen(true)}>Create Goal</Button>
          </Card>
        ) : (
          <div className="grid md:grid-cols-2 gap-6">
            {goals.map((goal) => (
              <Card key={goal.id} className="p-6">
                <div className="flex justify-between items-start mb-4">
                  <div>
                    <h3 className="text-xl font-semibold capitalize">{goal.goal_type.replace("_", " ")}</h3>
                    <p className="text-sm text-muted-foreground">
                      Target: {goal.target_value}
                      {goal.deadline && ` by ${new Date(goal.deadline).toLocaleDateString()}`}
                    </p>
                  </div>
                  <Button variant="ghost" size="icon" onClick={() => handleDeleteGoal(goal.id)}>
                    <Trash2 className="h-4 w-4 text-destructive" />
                  </Button>
                </div>
                {goal.current_value && (
                  <div className="space-y-2">
                    <div className="flex justify-between text-sm">
                      <span>Progress</span>
                      <span className="font-semibold">{getProgress(goal).toFixed(0)}%</span>
                    </div>
                    <div className="w-full bg-secondary rounded-full h-3">
                      <div
                        className="bg-accent h-3 rounded-full transition-all"
                        style={{ width: `${getProgress(goal)}%` }}
                      />
                    </div>
                    <p className="text-sm text-muted-foreground">
                      {goal.goal_type === "weight_loss" || goal.goal_type === "weight_gain"
                        ? `Starting: ${goal.current_value}kg / Current: ${latestLog?.weight || 'N/A'}kg / Target: ${goal.target_value}kg`
                        : goal.goal_type === "exercise"
                        ? `Daily Target: ${goal.target_value}min / Latest: ${latestLog?.exercise_minutes || 0}min`
                        : goal.goal_type === "blood_pressure"
                        ? `Target: ≤${goal.target_value} / Latest: ${latestLog?.blood_pressure_systolic || 'N/A'}/${latestLog?.blood_pressure_diastolic || 'N/A'}`
                        : goal.goal_type === "blood_glucose"
                        ? `Target: ≤${goal.target_value} / Latest: ${latestLog?.blood_glucose || 'N/A'}`
                        : `Current: ${goal.current_value} / Target: ${goal.target_value}`
                      }
                    </p>
                  </div>
                )}
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => handleViewPlan(goal)}
                  className="mt-2"
                  disabled={generating && selectedGoal?.id === goal.id}
                >
                  {generating && selectedGoal?.id === goal.id ? "Generating..." : dayPlan && selectedGoal?.id === goal.id ? "Hide Day Plan" : "View Day Plan"}
                </Button>
                {dayPlan && selectedGoal?.id === goal.id && (
                  <div className="mt-4 p-4 border rounded-lg bg-muted/50">
                    <h4 className="font-semibold mb-3">📅 Day-wise Plan</h4>
                    <Tabs defaultValue="Day 1" className="w-full">
                      <TabsList className="grid w-full grid-cols-7 mb-4">
                        {Object.keys(dayPlan).slice(0, 7).map((day) => (
                          <TabsTrigger key={day} value={day} className="text-xs">
                            {day}
                          </TabsTrigger>
                        ))}
                      </TabsList>
                      {Object.entries(dayPlan).slice(0, 7).map(([day, plan]) => (
                        <TabsContent key={day} value={day} className="space-y-3">
                          <div className="grid gap-3">
                            <div className="p-3 border rounded bg-white">
                              <h5 className="font-medium mb-1 text-sm">🍽️ Food</h5>
                              <p className="text-xs text-muted-foreground">{plan.food}</p>
                            </div>
                            <div className="p-3 border rounded bg-white">
                              <h5 className="font-medium mb-1 text-sm">🏃 Exercise</h5>
                              <p className="text-xs text-muted-foreground">{plan.exercise}</p>
                            </div>
                            <div className="p-3 border rounded bg-white">
                              <h5 className="font-medium mb-1 text-sm">📋 Activities</h5>
                              <p className="text-xs text-muted-foreground">{plan.activities}</p>
                            </div>
                            <div className="p-3 border rounded bg-yellow-50">
                              <h5 className="font-medium mb-1 text-sm">⏰ Reminder</h5>
                              <p className="text-xs text-muted-foreground">{plan.reminder}</p>
                            </div>
                          </div>
                        </TabsContent>
                      ))}
                    </Tabs>
                    <div className="flex gap-2 mt-4">
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => savePlanAsPDF(goal, dayPlan)}
                      >
                        <FileText className="h-4 w-4 mr-2" />
                        Save as PDF
                      </Button>
                    </div>
                  </div>
                )}
              </Card>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default Goals;
